ervices:
    traefik:
          image: "traefik:v2.10"
                container_name: "traefik"
                      command:
                              - "--api.insecure=true"
                                      - "--log.level=DEBUG"
                                              - "--providers.docker=true"
                                                      - "--providers.docker.exposedbydefault=false"
                                                              - "--entrypoints.web.address=:80"
                                                                      - "--entrypoints.websecure.address=:443"
                                                                              - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
                                                                                    ports:
                                                                                            - "80:80"
                                                                                                    - "8080:8080"
                                                                                                          volumes:
                                                                                                                  - "/var/run/docker.sock:/var/run/docker.sock"


                                                                                                                      testapp:
                                                                                                                            image: "testapp"
                                                                                                                                  labels:
                                                                                                                                          - "traefik.enable=true"
                                                                                                                                                  - "traefik.http.routers.testapp.rule=PathPrefix(`/`)"
                                                                                                                                                          - "traefik.http.middlewares.strip-lol.stripprefix.prefixes=/"
                                                                                                                                                                  - "traefik.http.middlewares.strip-lol.stripprefix.forceSlash=false"
                                                                                                                                                                          - "traefik.http.routers.testapp.middlewares=strip-lol@docker"
                                                                                                                                                                                  - "traefik.http.services.testapp.loadbalancer.server.port=5000"
                                                                                                                                                                                        restart: always
